name: dApp

on:
  push:
    branches:
      - main
    paths:
      - "dapp/**"
  pull_request:

defaults:
  run:
    working-directory: ./dapp

jobs:
  sdk-build:
    uses: ./.github/workflows/reusable-sdk-build.yaml

  dapp-format:
    needs: [sdk-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "dapp/.nvmrc"
          cache: "pnpm"

      - name: Download SDK Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: sdk-build
          path: sdk/dist

      - name: Install Dependencies
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Format
        run: pnpm run format

  dapp-build:
    needs: [sdk-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "dapp/.nvmrc"
          cache: "pnpm"

      - name: Download SDK Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: sdk-build
          path: sdk/dist

      - name: Install Dependencies
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Build
        run: pnpm run build
  dapp-test:
    needs: [sdk-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "dapp/.nvmrc"
          cache: "pnpm"

      - name: Download SDK Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: sdk-build
          path: sdk/dist

      - name: Install Dependencies
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Tests
        run: pnpm vitest run
