name: dApp

on:
  push:
    branches:
      - main
    paths:
      - "dapp/**"
  pull_request:

defaults:
  run:
    working-directory: ./dapp

jobs:
  dapp-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "dapp/.nvmrc"
          cache: "yarn"
          cache-dependency-path: "dapp/yarn.lock"

      - name: Install Dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Format
        run: yarn format
