name: Codegen the subgraph package
on:
  workflow_call:

jobs:
  subgraph-codegen:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./subgraph
    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "subgraph/.nvmrc"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Codegen
        run: pnpm run codegen

      - name: Upload Codegen Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: subgraph-codegen
          path: |
            subgraph/generated
          if-no-files-found: error
