name: Build the SDK package
on:
  workflow_call:

jobs:
  core-build:
    uses: ./.github/workflows/reusable-core-build.yaml

  sdk-build:
    defaults:
      run:
        working-directory: ./sdk
    needs: [core-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v2

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "sdk/.nvmrc"
          cache: "pnpm"

      - name: Download Core Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: core-build
          path: core/

      - name: Install Dependencies
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sdk-build
          path: sdk/dist/
          if-no-files-found: error
