name: Build the Solidity package
on:
  workflow_call:

jobs:
  build-solidity:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solidity
    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "solidity/.nvmrc"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: solidity-build
          path: |
            solidity/build/
            solidity/cache/
            solidity/typechain/
          if-no-files-found: error
