name: Website

on:
  push:
    branches:
      - main
    paths:
      - "website/**"
  pull_request:

defaults:
  run:
    working-directory: ./website

jobs:
  website-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Format
        run: pnpm run format

  website-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Build
        run: pnpm run build
